name = "gametheory_project"
uuid = "6c351062-e288-44b6-baad-5f38568d8823"
authors = ["Wenkai Qin <wqin@utexas.edu", "Jad Bourjeili <jadbourjeili@utexas.edu>"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
